network_config: Holesky
postgres:
  hostname: localhost
  port: 5432
  db_name: postgres
  user: postgres
  region: 0
  region_name: "LOCAL"
  # pool_size: 20
broadcasters:
  - !BeaconClient
    url: http://localhost:5052
simulators:
  - url: http://localhost:8545
beacon_clients:
  - url: http://localhost:5052
relays: []
builders: []
validator_preferences:
  filtering: regional
  trusted_builders: null
  header_delay: true
router_config:
  enabled_routes:
    - route: GetValidators
    - route: SubmitBlock
    - route: SubmitBlockOptimistic
    - route: ValidatorRegistration
    - route: GetHeader
      rate_limit:
        replenish_ms: 100
        burst_size: 10
    - route: GetPayload
    - route: ProposerPayloadDelivered
    - route: RegisterValidators
    - route: Status
block_merging_config:
  is_enabled: false
  max_merged_bid_age_ms: 250
  # tcp:
  #   builders:
  #     - addr: "127.0.0.1:9876"
  #       api_key: "00000000-0000-0000-0000-000000000001"
  #   relay_fee_recipient: "0x0000000000000000000000000000000000000000"
  #   multisend_contract: "0x0000000000000000000000000000000000000000"
  #   relay_bps: 2500
  #   merged_builder_bps: 2500
  #   winning_builder_bps: 2500
  #   distribution_gas_limit: 140000
  #   builder_collaterals:
  #     - builder_coinbase: "0x0000000000000000000000000000000000000000"
  #       collateral_safe: "0x0000000000000000000000000000000000000000"
target_get_payload_propagation_duration_ms: 0
primev_config: null
discord_webhook_url: null
is_submission_instance: true
is_registration_instance: true
logging: !File
  dir_path: /app/logs
  file_name: titan_relay.log
  otlp_server: http://localhost:4317
cores:
  auctioneer: 1
  sub_workers: [2, 3, 4, 5]
  reg_workers: [6, 7, 8, 9]
  tokio: [10, 11, 12, 13]
  # block_merging: 14
