network_config: Holesky
postgres:
  hostname: localhost
  port: 5432
  db_name: postgres
  user: postgres
  password: password
  region: 0
  region_name: "LOCAL"
broadcasters:
  - !BeaconClient
    url: http://localhost:5052
    gossip_blobs_enabled: false
simulators:
  - url: http://localhost:8545
beacon_clients:
  - url: http://localhost:5052
    gossip_blobs_enabled: false
relays: []
builders: []
validator_preferences:
  filtering: regional
  trusted_builders: null
  header_delay: true
  gossip_blobs: false
router_config:
  enabled_routes:
    - route: GetValidators
    - route: SubmitBlock
    - route: SubmitBlockOptimistic
    - route: ValidatorRegistration
    - route: GetHeader
      rate_limit:
        replenish_ms: 100
        burst_size: 10
    - route: GetPayload
    - route: ProposerPayloadDelivered
    - route: RegisterValidators
    - route: Status
block_merging_config:
  is_enabled: true
  max_merged_bid_age_ms: 250
target_get_payload_propagation_duration_ms: 0
primev_config: null
discord_webhook_url: null
logging: !File
  dir_path: /app/logs
  file_name: titan_relay.log
  otlp_server: http://localhost:4317
