FROM rust:1.75.0 as helix

RUN apt update -y
RUN apt install -y clang
RUN apt install -y protobuf-compiler

# Copy necessary contents into the container at /app
ADD . /app/

RUN ls -lah /app
RUN ls -lah /app/helix

# Set the working directory to /app
WORKDIR /app/helix

# Run build
RUN cargo build -p helix-cmd --release

# Copy binary into the workdir
RUN mv /app/$helix/target/release/helix-cmd /app/helix-cmd

# our final base
FROM debian:stable-slim

RUN mkdir /root/logs

RUN apt-get update
RUN apt-get install -y ca-certificates

WORKDIR /app

COPY config.yml /app/config.yml

COPY --from=helix /app/helix-cmd* ./

# set the startup command to run your binary
ENTRYPOINT ["/app/helix-cmd"]

