binop_separator = "Back"
comment_width = 120
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 100
overflow_delimited_expr = true
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
